-- Espace responsables de clubs.
-- À exécuter une seule fois dans Supabase > SQL Editor après 01_schema.sql et 02_rls_policies.sql.
-- Le mot de passe reste géré exclusivement par Supabase Auth et n'est jamais stocké dans ces tables.

create table if not exists public.club_profiles (
  id text primary key,
  name text not null,
  category text not null,
  tagline text not null,
  description text not null,
  founded_label text,
  recruitment_label text,
  contact_label text,
  contact_url text,
  objectives text[] not null default '{}',
  status text not null default 'active' check (status in ('active', 'hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.club_managers (
  user_id uuid not null references auth.users(id) on delete cascade,
  club_id text not null references public.club_profiles(id) on delete cascade,
  manager_role text not null default 'manager' check (manager_role in ('manager', 'president')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  primary key (user_id, club_id)
);

create table if not exists public.club_events (
  id uuid primary key default gen_random_uuid(),
  club_id text not null references public.club_profiles(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete restrict default auth.uid(),
  title text not null check (char_length(title) between 3 and 180),
  description text not null check (char_length(description) between 10 and 1200),
  location text not null,
  event_type text not null default 'Atelier',
  starts_at timestamptz not null,
  ends_at timestamptz,
  capacity integer check (capacity is null or capacity > 0),
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at is null or ends_at >= starts_at)
);

create table if not exists public.club_event_registrations (
  event_id uuid not null references public.club_events(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  status text not null default 'registered' check (status in ('registered', 'cancelled')),
  attended boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (event_id, user_id)
);

create table if not exists public.club_announcements (
  id uuid primary key default gen_random_uuid(),
  club_id text not null references public.club_profiles(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete restrict default auth.uid(),
  title text not null check (char_length(title) between 3 and 180),
  body text not null check (char_length(body) between 10 and 1200),
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.club_memberships (
  club_id text not null references public.club_profiles(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  application_id uuid references public.club_applications(id) on delete set null,
  status text not null default 'active' check (status in ('active', 'inactive')),
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (club_id, user_id)
);

create table if not exists public.club_profile_views (
  id bigint generated by default as identity primary key,
  club_id text not null references public.club_profiles(id) on delete cascade,
  viewer_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  viewed_at timestamptz not null default now()
);

create index if not exists club_events_club_status_idx
  on public.club_events (club_id, status, starts_at);
create index if not exists club_announcements_club_status_idx
  on public.club_announcements (club_id, status, created_at desc);
create index if not exists club_views_club_date_idx
  on public.club_profile_views (club_id, viewed_at desc);
create index if not exists club_memberships_club_status_idx
  on public.club_memberships (club_id, status);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'club_profiles', 'club_events', 'club_event_registrations',
    'club_announcements', 'club_memberships'
  ]
  loop
    execute format('drop trigger if exists set_%I_updated_at on public.%I', table_name, table_name);
    execute format(
      'create trigger set_%I_updated_at before update on public.%I for each row execute procedure public.set_updated_at()',
      table_name,
      table_name
    );
  end loop;
end $$;

insert into public.club_profiles (
  id, name, category, tagline, description, founded_label,
  recruitment_label, contact_label, contact_url, objectives
)
values (
  'innoverse',
  'InnoVerse',
  'Développement & innovation',
  'Imaginer, coder et transformer des idées en projets numériques.',
  'Le club d’innovation informatique de l’ENIAD réunit les étudiants intéressés par le développement, les API, le DevOps, l’intelligence artificielle et la création de produits numériques.',
  'Club technologique',
  'Candidatures ouvertes toute l’année',
  'Contacter InnoVerse',
  'https://www.linkedin.com/company/innoverseeniad',
  array[
    'Transformer les acquis techniques en produits numériques concrets.',
    'Créer des équipes pluridisciplinaires autour de défis réels.',
    'Développer la culture du partage et du mentorat entre promotions.'
  ]
)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  tagline = excluded.tagline,
  description = excluded.description,
  founded_label = excluded.founded_label,
  recruitment_label = excluded.recruitment_label,
  contact_label = excluded.contact_label,
  contact_url = excluded.contact_url,
  objectives = excluded.objectives;

-- Premier responsable InnoVerse : le compte Auth existant du propriétaire du portail.
insert into public.club_managers (user_id, club_id, manager_role)
select id, 'innoverse', 'president'
from auth.users
where lower(email) = lower('atrariabdennour642@gmail.com')
on conflict (user_id, club_id) do update set active = true, manager_role = 'president';

create or replace function private.manages_club(target_club_id text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.club_managers
    where user_id = (select auth.uid())
      and club_id = target_club_id
      and active = true
  ) or private.is_admin();
$$;

revoke execute on function private.manages_club(text) from public;
grant execute on function private.manages_club(text) to authenticated;

alter table public.club_profiles enable row level security;
alter table public.club_managers enable row level security;
alter table public.club_events enable row level security;
alter table public.club_event_registrations enable row level security;
alter table public.club_announcements enable row level security;
alter table public.club_memberships enable row level security;
alter table public.club_profile_views enable row level security;

revoke all on table public.club_profiles from anon;
revoke all on table public.club_managers from anon;
revoke all on table public.club_events from anon;
revoke all on table public.club_event_registrations from anon;
revoke all on table public.club_announcements from anon;
revoke all on table public.club_memberships from anon;
revoke all on table public.club_profile_views from anon;

grant select, update on table public.club_profiles to authenticated;
grant select on table public.club_managers to authenticated;
grant select, insert, update, delete on table public.club_events to authenticated;
grant select, insert, update, delete on table public.club_event_registrations to authenticated;
grant select, insert, update, delete on table public.club_announcements to authenticated;
grant select on table public.club_memberships to authenticated;
grant select, insert on table public.club_profile_views to authenticated;

drop policy if exists club_profiles_select_authenticated on public.club_profiles;
create policy club_profiles_select_authenticated
on public.club_profiles for select to authenticated using (status = 'active' or private.manages_club(id));

drop policy if exists club_profiles_update_manager on public.club_profiles;
create policy club_profiles_update_manager
on public.club_profiles for update to authenticated
using (private.manages_club(id)) with check (private.manages_club(id));

drop policy if exists club_managers_select_own on public.club_managers;
create policy club_managers_select_own
on public.club_managers for select to authenticated
using (user_id = (select auth.uid()) or private.is_admin());

drop policy if exists club_events_select_relevant on public.club_events;
create policy club_events_select_relevant
on public.club_events for select to authenticated
using (status = 'published' or private.manages_club(club_id));

drop policy if exists club_events_manage on public.club_events;
create policy club_events_manage
on public.club_events for all to authenticated
using (private.manages_club(club_id))
with check (private.manages_club(club_id) and created_by = (select auth.uid()));

drop policy if exists club_event_registrations_select_relevant on public.club_event_registrations;
create policy club_event_registrations_select_relevant
on public.club_event_registrations for select to authenticated
using (
  user_id = (select auth.uid())
  or exists (
    select 1 from public.club_events
    where club_events.id = event_id and private.manages_club(club_events.club_id)
  )
);

drop policy if exists club_event_registrations_insert_own on public.club_event_registrations;
create policy club_event_registrations_insert_own
on public.club_event_registrations for insert to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists club_event_registrations_update_relevant on public.club_event_registrations;
create policy club_event_registrations_update_relevant
on public.club_event_registrations for update to authenticated
using (
  user_id = (select auth.uid())
  or exists (
    select 1 from public.club_events
    where club_events.id = event_id and private.manages_club(club_events.club_id)
  )
);

drop policy if exists club_event_registrations_delete_own on public.club_event_registrations;
create policy club_event_registrations_delete_own
on public.club_event_registrations for delete to authenticated
using (user_id = (select auth.uid()));

drop policy if exists club_announcements_select_relevant on public.club_announcements;
create policy club_announcements_select_relevant
on public.club_announcements for select to authenticated
using (status = 'published' or private.manages_club(club_id));

drop policy if exists club_announcements_manage on public.club_announcements;
create policy club_announcements_manage
on public.club_announcements for all to authenticated
using (private.manages_club(club_id))
with check (private.manages_club(club_id) and created_by = (select auth.uid()));

drop policy if exists club_memberships_select_relevant on public.club_memberships;
create policy club_memberships_select_relevant
on public.club_memberships for select to authenticated
using (user_id = (select auth.uid()) or private.manages_club(club_id));

drop policy if exists club_profile_views_insert_own on public.club_profile_views;
create policy club_profile_views_insert_own
on public.club_profile_views for insert to authenticated
with check (viewer_id = (select auth.uid()));

drop policy if exists club_profile_views_select_manager on public.club_profile_views;
create policy club_profile_views_select_manager
on public.club_profile_views for select to authenticated
using (private.manages_club(club_id));

-- Étend la sécurité des candidatures créée dans 05_clubs.sql aux responsables de clubs.
drop policy if exists club_applications_select_relevant on public.club_applications;
create policy club_applications_select_relevant
on public.club_applications for select to authenticated
using (applicant_id = (select auth.uid()) or private.manages_club(club_id));

drop policy if exists club_applications_update_staff on public.club_applications;
create policy club_applications_update_staff
on public.club_applications for update to authenticated
using (private.manages_club(club_id))
with check (private.manages_club(club_id));

create or replace function public.review_club_application(
  application_id uuid,
  decision text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target public.club_applications%rowtype;
begin
  if decision not in ('accepted', 'refused') then
    raise exception 'Décision invalide';
  end if;

  select * into target
  from public.club_applications
  where id = application_id;

  if target.id is null or not private.manages_club(target.club_id) then
    raise exception 'Accès refusé';
  end if;

  update public.club_applications
  set status = decision,
      reviewed_by = (select auth.uid()),
      reviewed_at = now(),
      updated_at = now()
  where id = application_id;

  if decision = 'accepted' then
    insert into public.club_memberships (club_id, user_id, application_id, status)
    values (target.club_id, target.applicant_id, target.id, 'active')
    on conflict (club_id, user_id) do update
      set status = 'active', application_id = excluded.application_id, updated_at = now();
  end if;

  insert into public.notifications (user_id, title, body, link)
  values (
    target.applicant_id,
    case when decision = 'accepted' then 'Candidature acceptée' else 'Mise à jour de votre candidature' end,
    case when decision = 'accepted'
      then 'Votre demande pour rejoindre le club a été acceptée.'
      else 'Votre demande n’a pas été retenue pour cette campagne.'
    end,
    '/clubs/' || target.club_id
  );
end;
$$;

revoke execute on function public.review_club_application(uuid, text) from public;
grant execute on function public.review_club_application(uuid, text) to authenticated;

create or replace function public.notify_club_members(
  target_club_id text,
  notification_title text,
  notification_body text
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  sent_count integer;
begin
  if not private.manages_club(target_club_id) then
    raise exception 'Accès refusé';
  end if;
  if char_length(trim(notification_title)) < 3 or char_length(trim(notification_body)) < 5 then
    raise exception 'Notification incomplète';
  end if;

  insert into public.notifications (user_id, title, body, link)
  select user_id, trim(notification_title), trim(notification_body), '/clubs/' || target_club_id
  from public.club_memberships
  where club_id = target_club_id and status = 'active';

  get diagnostics sent_count = row_count;
  return sent_count;
end;
$$;

revoke execute on function public.notify_club_members(text, text, text) from public;
grant execute on function public.notify_club_members(text, text, text) to authenticated;

-- Pour ajouter plus tard un autre responsable :
-- 1. Créez son compte dans Supabase > Authentication > Users.
-- 2. Exécutez :
-- insert into public.club_managers (user_id, club_id, manager_role)
-- select id, 'identifiant-du-club', 'manager' from auth.users where lower(email) = lower('email@exemple.com');
